"""empty message

Revision ID: 3f4328277a3a
Revises: 
Create Date: 2018-11-05 17:12:20.914043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f4328277a3a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book_class', sa.Column('books', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book_class', 'books')
    # ### end Alembic commands ###
