"""empty message

Revision ID: 7a83e38a868f
Revises: c2612f5fa671
Create Date: 2018-11-20 11:06:29.058278

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a83e38a868f'
down_revision = 'c2612f5fa671'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bookId', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('title', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'title')
    op.drop_column('users', 'bookId')
    # ### end Alembic commands ###
