"""empty message

Revision ID: bdd6afa74598
Revises: db6f6927e3c0
Create Date: 2018-11-11 13:20:56.632403

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bdd6afa74598'
down_revision = 'db6f6927e3c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book_badges', sa.Column('book_id', sa.String(length=30), nullable=True))
    op.drop_column('book_badges', 'badges_id')
    op.add_column('user_badges', sa.Column('badge_id', sa.String(length=30), nullable=True))
    op.add_column('user_shares', sa.Column('share_times', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_shares', 'share_times')
    op.drop_column('user_badges', 'badge_id')
    op.add_column('book_badges', sa.Column('badges_id', mysql.VARCHAR(length=30), nullable=True))
    op.drop_column('book_badges', 'book_id')
    # ### end Alembic commands ###
