"""empty message

Revision ID: c2612f5fa671
Revises: a2a2748470dc
Create Date: 2018-11-19 11:50:22.497281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2612f5fa671'
down_revision = 'a2a2748470dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('openid', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'openid')
    # ### end Alembic commands ###
