"""empty message

Revision ID: d274a9699385
Revises: bfc23ff591c7
Create Date: 2018-11-11 10:38:06.089741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd274a9699385'
down_revision = 'bfc23ff591c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'user')
    # ### end Alembic commands ###
