"""empty message

Revision ID: da53b0e8219f
Revises: 3f4328277a3a
Create Date: 2018-11-06 13:36:35.166338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da53b0e8219f'
down_revision = '3f4328277a3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book_messages', sa.Column('fav', sa.Integer(), nullable=True))
    op.add_column('book_messages', sa.Column('time', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book_messages', 'time')
    op.drop_column('book_messages', 'fav')
    # ### end Alembic commands ###
