"""empty message

Revision ID: db6f6927e3c0
Revises: d274a9699385
Create Date: 2018-11-11 11:07:27.283177

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'db6f6927e3c0'
down_revision = 'd274a9699385'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_badges', sa.Column('book_id', sa.String(length=30), nullable=True))
    op.drop_column('user_badges', 'badges')
    op.add_column('user_favs', sa.Column('book_id', sa.String(length=30), nullable=True))
    op.drop_column('user_favs', 'favs')
    op.add_column('user_shares', sa.Column('book_id', sa.String(length=30), nullable=True))
    op.drop_column('user_shares', 'shares')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_shares', sa.Column('shares', mysql.VARCHAR(length=30), nullable=True))
    op.drop_column('user_shares', 'book_id')
    op.add_column('user_favs', sa.Column('favs', mysql.VARCHAR(length=30), nullable=True))
    op.drop_column('user_favs', 'book_id')
    op.add_column('user_badges', sa.Column('badges', mysql.VARCHAR(length=30), nullable=True))
    op.drop_column('user_badges', 'book_id')
    # ### end Alembic commands ###
