"""empty message

Revision ID: e5c463449e99
Revises: da53b0e8219f
Create Date: 2018-11-06 13:58:16.017621

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e5c463449e99'
down_revision = 'da53b0e8219f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book_class', 'books')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book_class', sa.Column('books', mysql.TEXT(), nullable=True))
    # ### end Alembic commands ###
